backend:
  name: git-gateway
  branch: main   # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    extension: "mdx"
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    identifier_field: slug
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "hidden", default: "slug"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "author", name: "author", widget: "string"}
      - {label: "Tags", name: "tag", widget: "select", multiple: true, options: ["ai","banking","spreadsheets","software","business-accounting","accounting","accounting-software", "analysis","accounting-automation","gst-compliance", "diwali","accounting-services","business", "cloud-accounting","revenue","indian-accounting", "invoicing-software","cloud-computing","gst", "automation","invoice","bookkeeping", "online-accounting","taxes","finance", "cloud-computing","gst-tax","business-accounting", "sme","profit","guidelines", "income-tax","gst","gstr","tally", "financial-planing","gold","investing", "investment","small-business","entrepreneurship","financial-accounting", "management","new-year","good-and-service-tax", "inventory-management","inventory-software","ecommerce", "india","news","growth", "blogging","blogging-tips","business-blogging","excel", "technology","myths","covid-19-financial-impact", "expence-management","best-accounting-software","finance", "financial-management","investors","startup"], required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}   
      - {label: "Short Description", name: "description", widget: "string", required: true}   
      - {label: "Body", name: "body", widget: "markdown"}
